apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data:
  username: YWRtaW4=
  password: MTIzNA==

---
apiVersion: v1
kind: Secret
metadata:
  name: mongo-express-secret
type: Opaque
data:
  mduser: YWRtaW4=
  mdpass: MTIzNA==
  meuser: YWRtaW4=
  mepass: MTIzNA==